# Generated by Django 5.2 on 2025-06-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Ativa', max_length=20, null=True, verbose_name='Status')),
                ('classes', models.ManyToManyField(to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['id'],
            },
        ),
    ]
