# Generated by Django 5.2 on 2025-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='classes',
            new_name='classesEnrollment',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_start',
            field=models.DateField(verbose_name='Data de Início'),
        ),
    ]
