# Generated by Django 5.2 on 2025-06-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especializacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('date_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], max_length=1, verbose_name='Genero')),
                ('address', models.CharField(max_length=200, verbose_name='Endereco')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Numero de Celular')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EspecializacaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('especializacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especializacao.especializacao')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
            ],
        ),
    ]
