# Generated by Django 5.2 on 2025-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especializacao', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especializacaoprofessor',
            options={'ordering': ['id'], 'verbose_name': 'Especializacao do Professor', 'verbose_name_plural': 'Especializacoes do Professor'},
        ),
        migrations.AddField(
            model_name='professor',
            name='especializacaoProfessor',
            field=models.ManyToManyField(blank=True, through='professores.EspecializacaoProfessor', to='especializacao.especializacao'),
        ),
    ]
