# Generated by Django 5.2 on 2025-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cellphone',
            field=models.CharField(default=1, max_length=10, verbose_name='Numero de Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='gender',
            field=models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], max_length=1, verbose_name='Genero'),
        ),
    ]
