# Generated by Django 5.2 on 2025-06-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('birth_year', models.DateField(max_length=4, verbose_name='Ano de Nascimento')),
                ('gender', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro')], max_length=1, verbose_name='Genero')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cell_phone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['id'],
            },
        ),
    ]
