# Generated by Django 5.2 on 2025-06-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplies', '0002_supply_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(max_length=4, verbose_name='Numero')),
                ('capacity', models.IntegerField(verbose_name='Capacidade')),
                ('supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supply')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['id'],
            },
        ),
    ]
