# Generated by Django 5.2 on 2025-06-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
